language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: y0pZn3XFyVJGb89dMXx5XMiHSN/otWTMLg6IGjcfP4GTisFUGeLa0IuDZUKue+4O4sTXZShH7OXC+tKO+uaiqs+5yCl3Ev5Zd5GP25ytN3UGbt8XeQ8EUhzf9mZh+C7QOFeLLvyA4WD33vRw0fnmDrYCDq1s2NDvOM7vULEURPrDfHw8q/Jg0AWl41iUE3zl/JCacU2mgVtqO1hoKIm7ZvX+SS7CxJKNcUgbz2Hik4Ngy9L3YgrHw59m3y7w84Bf0+a2SX8b0UWWqASwqrI2pdXPcfgTPYc60sd2sLckXsPXeadAxvaFXAp/NMThQq7wS5xtaXq+HgquyZz0fToT10zPnA05701jyq67lc1E7OV3XYZ3LdymaZiWZiS+2iJaTaJWrJE25QYrHliuD/zV0mpaBiNJ2uprpf6nQVf0RtUJKHlu+n7VfuAbIwole9wCTtsBLSGJreaCUa6yVFzsLExJft7GO0YrvdCKZAI5WiBHt94zizfyAn0Z0V0wumzVm/ZV5rmKFJ01BFKnz6kXZZxIsWhL9AJKyUlFmLmgxxXARdiB17CCJyhPav1PhcEAeGtTOMJGrTPXgS22/fQOriKYow1OcKytY9AjsyyNef8istZm0u3sxyFTHnn+bweWR4Fn/QVBIUkBaxoFM0e2uA2AHRTXS1KG5WxYynOw04A=
  app: 
  run: rails db:migrate
